
services:

  self-llm:
    build: 
      context: .
      dockerfile: Dockerfile
    image: self-llm
    container_name: self-llm
    runtime: nvidia
    ports:
      - "11434:11434" # ollama api
      - "80:8080"     # webui
    environment:
      WEBUI_SECRET_KEY: "google: read-about-webui-key"
    volumes:
      - .data/models:/srv/models                                           # The models
      - .data/ollama:/root/.ollama                                         # Some generated keys
      - .data/data:/usr/local/lib/python3.12/site-packages/open_webui/data # WebUI data folder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
